---
- include: "{{ ansible_distribution }}/main.yml"

- include: "shells/{{ ansible_user_shell.split('/')[-1] }}.yml"

- name: configre
  copy:
    src: starship.toml
    dest: "{{ lookup('env', 'HOME') }}/.config/starship.toml"
